### ISSUE TITLE
"Show Preview" command doesn't specify extension

### ISSUE THREAD

**Issue by drewrisinger** [jithurjacob/vscode-nbpreviewer#11]
# Issue
When running nbpreviewer, it is not clear what extension has the `Show preview` command. Most extensions say something like `Extension: command`.

# Fix
Should be able to change with simple fix to `package.json`. Need to set "category" field.

**Comment by jithurjacob** [comment]
Apologies for the delay. I was going through some personal issues. I have published a new version after testing on my MacBook Pro. Please confirm if the issue is solved.

**Comment by drewrisinger** [comment]
Tested, works properly. Thank you for responding, and best of luck with the personal issues.
