### ISSUE TITLE
Cannot read property 'document' of undefined.

### ISSUE THREAD

**Issue by flo-85** [jithurjacob/vscode-nbpreviewer#14]
I have just installed the extension, and I get the below error when trying to open any of my notebooks:

> Unable to open 'IPython Notebook Preview': Cannot read property 'document' of undefined.

**Comment by jrderuiter** [comment]
Same here :(

**Comment by SamKacer** [comment]
Same is happening for me. really a shame, as this would really improve my workflow if it worked.

**Comment by xingfanxia** [comment]
+1

**Comment by BryanWilhite** [comment]
Same here (and it might help to mention that I have a jupyter environment from Anaconda installed):

```console
Version: 1.28.2 (system setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by masip85** [comment]
+1

**Comment by jithurjacob** [comment]
Apologies for the delay. I was going through some personal issues. I have published a new version after testing on my MacBook Pro. Please confirm if the issue is solved.

**Comment by jithurjacob** [comment]
@masip85 @BryanWilhite @SamKacer @jrderuiter @flo-85 

Could you please provide a screen shot with your developer console open. Please follow the below steps.

1. Click Help > Toggle Developer Tools
2. Open a Jupyter notebook
<img width="1440" alt="screenshot 2018-12-15 at 12 04 28 pm" src="https://user-images.githubusercontent.com/7101452/50040004-014b0700-0062-11e9-8f2b-1998b555d055.png">

**Comment by SamKacer** [comment]
Hi,

I just checked and it works properly for me now. Thanks :)
