### ISSUE TITLE
Upgrade to VS Code's webview API 

### ISSUE THREAD

**Issue by mjbvz** [jithurjacob/vscode-nbpreviewer#16]
Hi, I'm on the VS Code team. I noticed that your extension uses the `vscode.previewHtml` command which is deprecated and which we are actively working to remove: https://github.com/Microsoft/vscode/issues/62630

We've developed a [webview API][docs] that provides a much better developer experience and offers a number of important security and compatibility benefits over `previewHtml`. We cannot fix `previewHtml` without breaking backwards compatibility, and have instead opted to remove it. 

To ensure that your extension continues to work properly in VS Code, please try upgrading to use the new Webview API. You can find documentation on the API usage [here][docs]. Let me know if you have any questions or concerns about this migration

[docs]: https://code.visualstudio.com/docs/extensions/webview

**Comment by noklam** [comment]
Please fix it, this is by far the best previewer. It's very handy to have a quick look on editor.

**Comment by jithurjacob** [comment]
Apologies for the delay. I was going through some personal issues. I have published a new version after testing on my MacBook Pro. Please confirm if the issue is solved.

@mjbvz  Thank you for taking the time to point me in the right direction
