### ISSUE TITLE
Dark Theme VS but Light background for preview

### ISSUE THREAD

**Issue by noklam** [jithurjacob/vscode-nbpreviewer#19]
Thanks for fixing the extension, it is very useful.

In the past, the notebook with render as  dark theme if my VSC is dark theme, but now it is always bright white background, is it possible to fix it?

![image](https://user-images.githubusercontent.com/18221871/50402509-282bda80-07d2-11e9-9d9d-dc8183d909a1.png)

**Comment by jithurjacob** [comment]
Thanks. I've updated the extension please try version 1.2.1

**Comment by noklam** [comment]
Hi @jithurjacob, thanks for quickly update it. I have test it with this notebook.

It would be great if you can also fix the markdown cell, I think it should be share similar style as the code block.

https://gist.github.com/noklam/7d80e66e5c5e06d4cb61df188a6a9b6d
![image](https://user-images.githubusercontent.com/18221871/50416293-ccf1fa80-085a-11e9-96d3-7ee4d0f078f3.png)

**Comment by jithurjacob** [comment]
Fixed markdown rendering in V1.2.2

**Comment by noklam** [comment]
Thanks dude! Works beautifully in any theme now.

![image](https://user-images.githubusercontent.com/18221871/50424243-31817980-089c-11e9-9e7b-b90c972a2080.png)
![image](https://user-images.githubusercontent.com/18221871/50424247-3a724b00-089c-11e9-8fe3-8234b85e95df.png)

**Comment by jithurjacob** [comment]
Awesome, thank you for testing. Closing the issue.
