### ISSUE TITLE
Preview not properly rendered

### ISSUE THREAD

**Issue by parthi2929** [jithurjacob/vscode-nbpreviewer#21]
**Describe the bug**
The white background in notebook is grey in preview as shown below. 

**To Reproduce**
Just open any notebook and show preview

**Screenshots**
![2019-02-07_18h23_26](https://user-images.githubusercontent.com/11896263/52412712-8f44ea80-2b05-11e9-81c5-5226ed8675a3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by jithurjacob** [comment]
This is by design(too lazy to write custom colors for all scenarios). Feel free to raise a PR.

**Comment by parthi2929** [comment]
But in your preview gif, the notebook shows properly?
