### ISSUE TITLE
Cannot read property 'name' of undefined.

### ISSUE THREAD

**Issue by xunhs** [jithurjacob/vscode-nbpreviewer#3]
I download my ipynb from https://colab.research.google.com/notebooks/welcome.ipynb. When i open it in vscode, it inform me that TypeError: Cannot read property 'name' of undefined. But there is no problem when i open it in jupyter notebook.
Thanks.

**Comment by metya** [comment]
The same problem with some notebooks.

**Comment by Chistabo** [comment]
I have same issue, it repeats every time:
Using MagicPython language:
- I click on jupyter file, i.e. ClassificationDemo-Python.ipynb, to open it in VSCode, in editor #1 (left one)
- I click 'Show preview', and VSCode opens a preview, no problemo; I can view it in another editor (#2, right one)
- I have another python file opened in editor #2, and when I switch focus on this file, and then back to preview in editor #2, I get an error message - 'Unable to open 'IPython Notebook Preview': Cannot read property 'document' of undefined.'
So, while switching (cursor focus) between
ClassificationDemo-Python.ipynb
and
ClassificationDemo-Python.ipynb preview,
there are no problems. When focus is on another file, and back to preview, error appears.

Simon
S love nia

**Comment by clemens-tolboom** [comment]
See PR #7
