### ISSUE TITLE
Latex formulae in preview

### ISSUE THREAD

**Issue by metya** [jithurjacob/vscode-nbpreviewer#4]
Hi! Extension is amazing. Thanks for that.

But is there way to render Latex or Katex formulae on preview mode? This is actually quite important feature for me and i think for most people who work with jupyter notebooks.

**Comment by jithurjacob** [comment]
Hi @metya thank you. The extension depends on notebookjs for rendering. Latex support hasn't yet been merged with the library. Once it is done we can use that Latex rendering.

https://github.com/jsvine/notebookjs/issues/11

**Comment by jithurjacob** [comment]
@metya I've added support for Latex rendering in V1.2.2
